version: "2"

services:

  rabbit:
      hostname: rabbit
      image: rabbitmq:latest
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      ports:
          - "5672:5672"
  api:
    build:
      context: .
    ports:
      - 8000:8000

  celery-worker:
      build:
        context: .
      container_name: celery-worker
      entrypoint: celery
      command:  -A Youtube worker --loglevel=INFO
      network_mode: host
      depends_on:
        - rabbit

  celery-beat:
      build:
        context: .
      container_name: celery-beat
      entrypoint: celery
      command: -A Youtube beat --loglevel=INFO
      network_mode: host
      depends_on:
        - celery-worker