# Generated by Django 3.1.1 on 2021-09-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('publishedAt', models.DateTimeField(db_index=True)),
                ('channelTitle', models.CharField(max_length=200)),
            ],
        ),
    ]
